apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: trafficcontrol-secrets
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName
    value: kv-dapr-ussc-demo
  - name: spnTenantId
    value: 72f988bf-86f1-41af-91ab-2d7cd011db47
  - name: spnClientId
    value: 1d62c4a7-287d-47ec-9e31-6c9c382ed0d2
  - name: spnCertificate
    secretKeyRef:
      name: sp-dapr-workshop-ussc-demo
      key: sp-dapr-workshop-ussc-demo
  - name: nestedSeparator
    value: "-"
scopes:
- finecollectionservice   
auth:
  secretStore: kubernetes
