apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulation
  labels:
    app: simulation 
spec:
  replicas: 0
  selector:
    matchLabels:
      app: simulation
  template:
    metadata:
      labels:
        app: simulation
    spec:
      containers:
      - name: simulation
        image: crdaprusscdemo.azurecr.io/simulation:assignment08
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 200Mi
      imagePullSecrets:
      - name: dapr-acr-pull-secret
              